export const PHYSICAL_PROPERTY_MAP: Record<string, string> = {
  'padding-top': 'padding-block-start',
  'padding-bottom': 'padding-block-end',
  'padding-left': 'padding-inline-start',
  'padding-right': 'padding-inline-end',
  'margin-top': 'margin-block-start',
  'margin-bottom': 'margin-block-end',
  'margin-left': 'margin-inline-start',
  'margin-right': 'margin-inline-end',
  'border-top': 'border-block-start',
  'border-bottom': 'border-block-end',
  'border-left': 'border-inline-start',
  'border-right': 'border-inline-end',
  'border-top-width': 'border-block-start-width',
  'border-bottom-width': 'border-block-end-width',
  'border-left-width': 'border-inline-start-width',
  'border-right-width': 'border-inline-end-width',
  'border-top-style': 'border-block-start-style',
  'border-bottom-style': 'border-block-end-style',
  'border-left-style': 'border-inline-start-style',
  'border-right-style': 'border-inline-end-style',
  'border-top-color': 'border-block-start-color',
  'border-bottom-color': 'border-block-end-color',
  'border-left-color': 'border-inline-start-color',
  'border-right-color': 'border-inline-end-color',
  'border-top-left-radius': 'border-start-start-radius',
  'border-top-right-radius': 'border-start-end-radius',
  'border-bottom-left-radius': 'border-end-start-radius',
  'border-bottom-right-radius': 'border-end-end-radius',
  top: 'inset-block-start',
  bottom: 'inset-block-end',
  left: 'inset-inline-start',
  right: 'inset-inline-end',
  width: 'inline-size',
  height: 'block-size',
  'min-width': 'min-inline-size',
  'min-height': 'min-block-size',
  'max-width': 'max-inline-size',
  'max-height': 'max-block-size',
  'overflow-x': 'overflow-inline',
  'overflow-y': 'overflow-block',
  'overscroll-behavior-x': 'overscroll-behavior-inline',
  'overscroll-behavior-y': 'overscroll-behavior-block',
  'scroll-padding-top': 'scroll-padding-block-start',
  'scroll-padding-bottom': 'scroll-padding-block-end',
  'scroll-padding-left': 'scroll-padding-inline-start',
  'scroll-padding-right': 'scroll-padding-inline-end',
  'scroll-margin-top': 'scroll-margin-block-start',
  'scroll-margin-bottom': 'scroll-margin-block-end',
  'scroll-margin-left': 'scroll-margin-inline-start',
  'scroll-margin-right': 'scroll-margin-inline-end',
  'contain-intrinsic-width': 'contain-intrinsic-inline-size',
  'contain-intrinsic-height': 'contain-intrinsic-block-size',
};

export const POSITION_DEPENDENT_PROPERTIES = new Set(['top', 'right', 'bottom', 'left']);

export const STATEFUL_PSEUDO_CLASSES = [
  'hover',
  'focus',
  'active',
  'visited',
  'focus-within',
  'focus-visible',
  'target',
  'checked',
  'disabled',
  'enabled',
];
